const COMPANYINFO = 'COMPANYINFO';
const COMPANYINFO_ERROR = 'COMPANYINFO_ERROR';
const COMPANYTYPE = 'COMPANYTYPE';
const COMPANYTYPE_ERROR = 'COMPANYTYPE_ERROR';
const COMPANYTYPE_JURISDICTION = 'COMPANYTYPE_JURISDICTION';
const AUTH_COMPANY_INFO_SUCCESS = 'AUTH_COMPANY_INFO_SUCCESS';

export {
    COMPANYINFO,
    COMPANYINFO_ERROR,
    COMPANYTYPE,
    COMPANYTYPE_ERROR,
    COMPANYTYPE_JURISDICTION,
    AUTH_COMPANY_INFO_SUCCESS
}