const GROUP_LIST_JUR='GROUP_LIST_JUR';
const GROUP_STATUS_SUCCESS='GROUP_STATUS_SUCCESS';
const GROUP_LIST_ACTION = 'GROUP_LIST_ACTION';
const GROUP_LIST = 'GROUP_LIST';
const GROUP_EDIT_ACTION = 'GROUP_EDIT_ACTION';
const GROUP_EDIT = 'GROUP_EDIT';
const GROUP_COPY_ACTION = 'GROUP_COPY_ACTION';
const GROUP_COPY = 'GROUP_COPY';
const GROUP_DEL_ACTION = 'GROUP_DEL_ACTION';
const GROUP_DEL = 'GROUP_DEL';

const GROUP_MEMBER_ACTION = 'GROUP_MEMBER_ACTION';
const GROUP_MEMBER = 'GROUP_MEMBER';
const GROUP_MEMBER_DEL_ACTION = 'GROUP_MEMBER_DEL_ACTION';
const GROUP_MEMBER_DEL = 'GROUP_MEMBER_DEL';

export {
    GROUP_STATUS_SUCCESS,
    GROUP_LIST_JUR,
    GROUP_LIST_ACTION,
    GROUP_LIST,
    GROUP_EDIT_ACTION,
    GROUP_EDIT,
    GROUP_COPY_ACTION,
    GROUP_COPY,
    GROUP_DEL_ACTION,
    GROUP_DEL,

    GROUP_MEMBER_ACTION,
    GROUP_MEMBER,
    GROUP_MEMBER_DEL_ACTION,
    GROUP_MEMBER_DEL,
}