const DISPUTE_LIST='DISPUTE_LIST';
const DISPUTE_INFO='DISPUTE_INFO';
const DISPUTE_AUDIT='DISPUTE_AUDIT';
const DISPUTE_JURISDICTION='DISPUTE_JURISDICTION';

export {
    DISPUTE_LIST,DISPUTE_INFO,DISPUTE_AUDIT,DISPUTE_JURISDICTION
}
