export const PACKET_LIST_ACTION = 'PACKET_LIST_ACTION';
export const PACKET_LIST_SUCCESS = 'PACKET_LIST_SUCCESS';

export const PACKET_SELECT_COMISSON_ACTION = 'PACKET_SELECT_COMISSON_ACTION';
export const PACKET_SELECT_COMISSON_SUCCESS = 'PACKET_SELECT_COMISSON_SUCCESS';

export const PACKET_SELECT_COMISSON_DELETE = 'PACKET_SELECT_COMISSON_DELETE';

export const PACKET_SELECT_COMISSON_ADD = 'PACKET_SELECT_COMISSON_ADD';

export const PACKET_SELECT_COMISSON_UPDATE = 'PACKET_SELECT_COMISSON_UPDATE';

export const PACKET_SELECT_COMISSON_UPDATE_SUC = 'PACKET_SELECT_COMISSON_UPDATE_SUC';

export const PACKET_JUR = 'PACKET_JUR';