const ORGANIZATION_STATUS_SUCCESS= 'ORGANIZATION_STATUS_SUCCESS';
const ORGANIZATION_ERROR='ORGANIZATION_ERROR';
const ORGANIZATION_ACTION='ORGANIZATION_ACTION';
const ORGANIZATION_LIST='ORGANIZATION_LIST';
const ORGANIZATION_DELETE_ACTION='ORGANIZATION_DELETE_ACTION';
const ORGANIZATION_DELETE='ORGANIZATION_DELETE';
const ORGANIZATION_AUDIT_ACTION='ORGANIZATION_AUDIT_ACTION';
const ORGANIZATION_AUDIT='ORGANIZATION_AUDIT';

const ORGANIZATION_DETAIL_INFO_ACTION='ORGANIZATION_DETAIL_INFO_ACTION';
const ORGANIZATION_DETAIL_INFO='ORGANIZATION_DETAIL_INFO';
const ORGANIZATION_JUR='ORGANIZATION_JUR';

export {
    ORGANIZATION_JUR,
    ORGANIZATION_STATUS_SUCCESS,
    ORGANIZATION_ERROR,
    ORGANIZATION_ACTION, 
    ORGANIZATION_LIST, // 企业列表
    ORGANIZATION_DELETE_ACTION,
    ORGANIZATION_DELETE,// 删除
    ORGANIZATION_AUDIT_ACTION,
    ORGANIZATION_AUDIT, // 审核
    
    ORGANIZATION_DETAIL_INFO_ACTION,
    ORGANIZATION_DETAIL_INFO // 用户详情
};