export const GET_TASK_LIST_ACTION = 'GET_TASK_LIST_ACTION';
export const GET_TASK_LIST_SUCCESS = 'GET_TASK_LIST_SUCCESS';
export const GET_TASK_LIST_JUR = 'GET_TASK_LIST_JUR';

export const GET_TASK_HANDLE_ACTION = 'GET_TASK_HANDLE_ACTION';
export const GET_TASK_HANDLE_SUCCESS = 'GET_TASK_HANDLE_SUCCESS';

export const GET_TASK_MODAL_ACTION = 'GET_TASK_MODAL_ACTION';
export const GET_TASK_MODAL_SUCCESS = 'GET_TASK_MODAL_SUCCESS';

export const GET_TASK_TYPE_ACTION = 'GET_TASK_TYPE_ACTION';
export const GET_TASK_TYPE_SUCCESS = 'GET_TASK_TYPE_SUCCESS';

export const GET_TASK_MODAL_ADD_ACTION = 'GET_TASK_MODAL_ADD_ACTION';