const ASSISTANT_LIST_SUCCESS = 'ASSISTANT_LIST_SUCCESS';
const ASSISTANT_ERROR = 'ASSISTANT_ERROR';
const ASSISTANT_NAME_SUCCESS = 'ASSISTANT_NAME_SUCCESS';
const ASSISTANT_EDIT_SUCCESS = 'ASSISTANT_EDIT_SUCCESS';
const ASSISTANT_LIST_JURISDICTION = 'ASSISTANT_LIST_JURISDICTION';

export {
    ASSISTANT_LIST_SUCCESS,
    ASSISTANT_ERROR,
    ASSISTANT_EDIT_SUCCESS,
    ASSISTANT_LIST_JURISDICTION,
    ASSISTANT_NAME_SUCCESS
}