const DEFAULTAUTHLIST = 'DEFAULTAUTHLIST';
const DEFAULTAUTHLIST_ERROR = 'DEFAULTAUTHLIST_ERROR';
const AUTHLIST = 'AUTHLIST';
const AUTHLIST_ERROR = 'AUTHLIST_ERROR';
const DEFAULTAUTHLIST_JURISDICTION = 'DEFAULTAUTHLIST_JURISDICTION';

export {
    DEFAULTAUTHLIST,
    DEFAULTAUTHLIST_ERROR,
    AUTHLIST,
    AUTHLIST_ERROR,
    DEFAULTAUTHLIST_JURISDICTION
}