export const DASHBOARD_MY_TEAM = 'DASHBOARD_MY_TEAM';
export const DASHBOARD_LIST_JURISDICTION = 'DASHBOARD_LIST_JURISDICTION';
export const CREATE_PROJECT = 'CREATE_PROJECT';

export const DASHOBADR_LIST_INIT = 'DASHOBADR_LIST_INIT';
