const COMPANY_JUR='COMPANY_JUR';
const COMPANY_ERROR='COMPANY_ERROR';
const COMPANY_ACTION='COMPANY_ACTION';
const COMPANY_LIST='COMPANY_LIST';
const COMPANY_DELETE_ACTION='COMPANY_DELETE_ACTION';
const COMPANY_DELETE='COMPANY_DELETE';
const COMPANY_BSYSTEM_ACTION='COMPANY_BSYSTEM_ACTION';
const COMPANY_BSYSTEM='COMPANY_BSYSTEM';
const COMPANY_AUDIT='COMPANY_AUDIT';


const COMPANY_DETAIL_INFO_ACTION='COMPANY_DETAIL_INFO_ACTION';
const COMPANY_DETAIL_INFO='COMPANY_DETAIL_INFO';
const COMPANY_DETAIL_EDIT_ACTION='COMPANY_DETAIL_EDIT_ACTION';
const COMPANY_DETAIL_EDIT_SUCCESS='COMPANY_DETAIL_EDIT_SUCCESS';

export {
    COMPANY_JUR,
    COMPANY_ERROR,
    COMPANY_AUDIT,// 审核
    COMPANY_ACTION, 
    COMPANY_LIST, // 企业列表
    COMPANY_DELETE_ACTION,
    COMPANY_DELETE,// 删除
    COMPANY_BSYSTEM_ACTION,// 代管
    COMPANY_BSYSTEM,
    
    COMPANY_DETAIL_INFO_ACTION,
    COMPANY_DETAIL_INFO, // 用户详情
    COMPANY_DETAIL_EDIT_ACTION,
    COMPANY_DETAIL_EDIT_SUCCESS, // 用户编辑状态控制

};