
const ACCOUNT_DETAIL_STATUS_SUCCESS='ACCOUNT_DETAIL_STATUS_SUCCESS';

const ACCOUNT_DETAIL_INFO_ACTION='ACCOUNT_DETAIL_INFO_ACTION';
const ACCOUNT_DETAIL_INFO='ACCOUNT_DETAIL_INFO';
const ACCOUNT_DETAIL_EDIT_ACTION='ACCOUNT_DETAIL_EDIT_ACTION';
const MYCOUNT_JUR='MYCOUNT_JUR';


export {
    MYCOUNT_JUR,
    ACCOUNT_DETAIL_INFO_ACTION,
    ACCOUNT_DETAIL_INFO, // 用户详情
    ACCOUNT_DETAIL_EDIT_ACTION,


    ACCOUNT_DETAIL_STATUS_SUCCESS, // 用户编辑状态控制

};