const AUTHINFO = 'AUTHINFO';
const AUTHINFO_SUCCESS = 'AUTHINFO_SUCCESS';
const AUTHINFO_ERROR = 'AUTHINFO_ERROR';
const  AUTHINFO_JURISDICTION = ' AUTHINFO_JURISDICTION';

export {
    AUTHINFO,
    AUTHINFO_SUCCESS,
    AUTHINFO_ERROR,
    AUTHINFO_JURISDICTION
}