export const PLATFORM_JURISDICTION_LIST_ACTION = 'PLATFORM_JURISDICTION_LIST_ACTION';
export const PLATFORM_JURISDICTION_LIST_SUCCESS = 'PLATFORM_JURISDICTION_LIST_SUCCESS';
export const PLATFORM_JURISDICTION_LIST_JUR = 'PLATFORM_JURISDICTION_LIST_JUR';

export const PLATFORM_SEARCH_USER_ACTION = 'PLATFORM_SEARCH_USER_ACTION';
export const PLATFORM_SEARCH_USER_SUCCESS = 'PLATFORM_SEARCH_USER_SUCCESS';

export const PLATFORM_USER_GROUP_CLEAR = 'PLATFORM_USER_GROUP_CLEAR';

export const PLATFORM_JURISDICTION_SAVE_ACTION = 'PLATFORM_JURISDICTION_SAVE_ACTION';
export const PLATFORM_JURISDICTION_SAVE_SUCCESS = 'PLATFORM_JURISDICTION_SAVE_SUCCESS';

export const PLATFORM_JURISDICTION_DEL_ACTION = 'PLATFORM_JURISDICTION_DEL_ACTION';
export const PLATFORM_JURISDICTION_GET_DEL_SUCCESS = 'PLATFORM_JURISDICTION_GET_DEL_SUCCESS';
export const PLATFORM_JURISDICTION_GET_DEL_ACTION = 'PLATFORM_JURISDICTION_GET_DEL_ACTION';
export const PLATFORM_JURISDICTION_DEL_SUCCESS = 'PLATFORM_JURISDICTION_DEL_SUCCESS';
export const PLATFORM_JUST_DEL_CLEAR = 'PLATFORM_JUST_DEL_CLEAR';