const DEU_QUES_SUCCESS='DEU_QUES_SUCCESS';
const DEU_QUES_POINT_SUCCESS='DEU_QUES_POINT_SUCCESS';
const DEU_QUES_JUR='DEU_QUES_JUR';
const EDUCATION_LIST_ACTION='EDUCATION_LIST_ACTION';
const EDUCATION_LIST='EDUCATION_LIST';
const EDUCATION_INFO_ACTION= 'EDUCATION_INFO_ACTION';
const EDUCATION_INFO= 'EDUCATION_INFO';

const EDUQUES_DEL_ACTION = 'EDUQUES_DEL_ACTION';
const EDUQUES_SAVE_ACTION='EDUQUES_SAVE_ACTION';
const EDUQUES_LABEL_ADD_ACTION='EDUQUES_LABEL_ADD_ACTION';
const EDUQUES_LABEL_DEL_ACTION='EDUQUES_LABEL_DEL_ACTION';
const EDUQUES_POINT_ADD_ACTION='EDUQUES_POINT_ADD_ACTION';
const EDUQUES_POINT_DEL_ACTION='EDUQUES_POINT_DEL_ACTION';

export{
    DEU_QUES_SUCCESS,DEU_QUES_JUR,DEU_QUES_POINT_SUCCESS,
    EDUQUES_DEL_ACTION,EDUQUES_SAVE_ACTION,EDUQUES_LABEL_ADD_ACTION,EDUQUES_LABEL_DEL_ACTION,EDUQUES_POINT_ADD_ACTION,EDUQUES_POINT_DEL_ACTION,
    EDUCATION_LIST_ACTION,EDUCATION_LIST,
    EDUCATION_INFO_ACTION,EDUCATION_INFO
}