const PROJECT_COMPANY_LIST = 'PROJECT_COMPANY_LIST';
const PROJECT_COMPANY_ERROR = 'PROJECT_COMPANY_ERROR';
const PRO_COMPANY_JURISDICTION = 'PRO_COMPANY_JURISDICTION';
export {
    PROJECT_COMPANY_LIST,
    PRO_COMPANY_JURISDICTION,
    PROJECT_COMPANY_ERROR,
};

