const EDU_ASSIS_EDIT_SUCCESS = 'EDU_ASSIS_EDIT_SUCCESS';
const EDU_ASSIS_JUR='EDU_ASSIS_JUR';
// 教育助手列表
const EDU_ASSIS_LIST_ACTION='EDU_ASSIS_LIST_ACTION';
const EDU_ASSIS_LIST='EDU_ASSIS_LIST';
const EDU_ASSIS_EDIT_ACTION='EDU_ASSIS_EDIT_ACTION';
const EDU_ASSIS_COPY_ACTION='EDU_ASSIS_COPY_ACTION';
const EDU_ASSIS_DEL_ACTION='EDU_ASSIS_DEL_ACTION';

export{
    EDU_ASSIS_JUR,
    EDU_ASSIS_EDIT_SUCCESS,
    EDU_ASSIS_LIST_ACTION,EDU_ASSIS_LIST,
    EDU_ASSIS_EDIT_ACTION,
    EDU_ASSIS_COPY_ACTION,
    EDU_ASSIS_DEL_ACTION,
}