export const MENUS_SUCCESS = 'MENUS_SUCCESS';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const ERROR_MSG = 'ERROR_MSG';
export const DASHBOARD_MY_TEAM = 'DASHBOARD_MY_TEAM';
export const CHANGE_TOP_COMPANY = 'CHANGE_TOP_COMPANY';

export const CALLBACK_A_SYSTEM_SUCCESS = 'CALLBACK_A_SYSTEM_SUCCESS';
export const HOME_STORE_CLEAR = 'HOME_STORE_CLEAR';