export const JURISDICTION_LIST_ACTION = 'JURISDICTION_LIST_ACTION';
export const JURISDICTION_LIST_SUCCESS = 'JURISDICTION_LIST_SUCCESS';

export const JURISDICTION_NEW_LIST_ACTION = 'JURISDICTION_NEW_LIST_ACTION';
export const JURISDICTION_NEW_LIST_SUCCESS = 'JURISDICTION_NEW_LIST_SUCCESS';

export const JURISDICTION_NEW_LIST_SAVE_ACTION = 'JURISDICTION_NEW_LIST_SAVE_ACTION';
export const JURISDICTION_NEW_LIST_SAVE_SUCCESS = 'JURISDICTION_NEW_LIST_SAVE_SUCCESS';

export const JURISDICTION_NEW_LIST_UPDATE_CHECKED = 'JURISDICTION_NEW_LIST_UPDATE_CHECKED';

export const JURISDICTION_EDIT_ACTION = 'JURISDICTION_EDIT_ACTION';
export const JURISDICTION_ASSISTANT_UPDATE = 'JURISDICTION_ASSISTANT_UPDATE';

export const JURISDICTION_COPY_ACTION = 'JURISDICTION_COPY_ACTION';
export const JURISDICTION_DEL_ACTION = 'JURISDICTION_DEL_ACTION';

export const JURISDICTION_DETAIL_LIST_ACTION = 'JURISDICTION_DETAIL_LIST_ACTION';
export const JURISDICTION_DETAIL_LIST_SUCCESS = 'JURISDICTION_DETAIL_LIST_SUCCESS';

export const JURISDICTION_DETAIL_FETCH_USER_ACTION = 'JURISDICTION_DETAIL_FETCH_USER_ACTION';
export const JURISDICTION_DETAIL_FETCH_USER_SUCCESS = 'JURISDICTION_DETAIL_FETCH_USER_SUCCESS';

export const JURISDICTION_DETAIL_CLEAR_USERLIST = 'JURISDICTION_DETAIL_CLEAR_USERLIST';

export const JURISDICTION_DETAIL_UPDATE_ACTION = 'JURISDICTION_DETAIL_UPDATE_ACTION';

export const JURISDICTION_DETAIL_PRO_ACTION = 'JURISDICTION_DETAIL_PRO_ACTION';
export const JURISDICTION_DETAIL_PRO_SUCCESS = 'JURISDICTION_DETAIL_PRO_SUCCESS';

export const JURISDICTION_LIST_JUR = 'JURISDICTION_LIST_JUR';