
//删除项目
const DEL_PRO_SUCCESS='DEL_PRO_SUCCESS';
const DETAIL_PRO_SUCCESS='DETAIL_PRO_SUCCESS';
const PRO_DETAIL_ERROR='PRO_DETAIL_ERROR';
const PRO_DETAIL_JURISDICTION='PRO_DETAIL_JURISDICTION';

const UNIT_LIST_SUCCESS = 'UNIT_LIST_SUCCESS'; // 获取单位列表

export {
    PRO_DETAIL_JURISDICTION,
    DEL_PRO_SUCCESS,
    DETAIL_PRO_SUCCESS,
    PRO_DETAIL_ERROR,
    UNIT_LIST_SUCCESS
};
