const SECURITYINFO = 'SECURITYINFO';
const SECURITYINFO_UPDATE_PHONE = 'SECURITYINFO_UPDATE_PHONE';
const SECURITYINFO_ERROR = 'SECURITYINFO_ERROR';
const SECURITYINFO_JURISDICTION = 'SECURITYINFO_JURISDICTION';

export {
    SECURITYINFO,
    SECURITYINFO_ERROR,
    SECURITYINFO_UPDATE_PHONE,
    SECURITYINFO_JURISDICTION
}
