const ATTENDANCE_LIST = 'ATTENDANCE_LIST';
const ATTENDANCE_DETAIL = 'ATTENDANCE_DETAIL';
const ATTENDANCE_JURISDICTION = 'ATTENDANCE_JURISDICTION';

export {
    ATTENDANCE_LIST,
    ATTENDANCE_DETAIL,
    ATTENDANCE_JURISDICTION,
}