const PROJECT_SECTION_LIST = 'PROJECT_SECTION_LIST';
const PROJECT_COMPANY_ERROR = 'PROJECT_COMPANY_ERROR';
const PROJECT_COMPANY_EDIT = 'PROJECT_COMPANY_EDIT';
const PRO_SECTION_JURISDICTION = 'PRO_SECTION_JURISDICTION';
const PROJECT_COMPANY_ADD = 'PROJECT_COMPANY_ADD';
export {
    PROJECT_SECTION_LIST,
    PROJECT_COMPANY_ADD,
    PRO_SECTION_JURISDICTION,
    PROJECT_COMPANY_ERROR,
    PROJECT_COMPANY_EDIT,
};
