const USER_ERROR='USER_ERROR';
const USER_SUCCESS='USER_SUCCESS';
const USERMANAGE_JUR='USERMANAGE_JUR';

const USER_ACTION='USER_ACTION';
const USER_LIST='USER_LIST';
const USER_GROUP_ACTION='USER_GROUP_ACTION';
const USER_GROUP_LIST='USER_GROUP_LIST';
const USER_DELETE_ACTION='USER_DELETE_ACTION';

const USER_DETAIL_BLACK_ACTION='USER_DETAIL_BLACK_ACTION';
const USER_DETAIL_INFO_ACTION='USER_DETAIL_INFO_ACTION';
const USER_DETAIL_INFO='USER_DETAIL_INFO';

export {
    USER_ERROR,
    USERMANAGE_JUR,
    USER_SUCCESS,
    USER_ACTION, 
    USER_LIST, // 用户列表
    USER_GROUP_ACTION,
    USER_GROUP_LIST,// 用户组
    USER_DELETE_ACTION,// 删除
    USER_DETAIL_BLACK_ACTION,// 加入黑名单
    USER_DETAIL_INFO_ACTION,
    USER_DETAIL_INFO // 用户详情
};