export const EMPLOY_LIST = 'EMPLOY_LIST';
export const DEPARTMENT_LIST = 'DEPARTMENT_LIST';
export const PERSON_LIST = 'PERSON_LIST';
export const PERSON_ERROR = 'PERSON_ERROR';
export const EMPLOY_LIST_JURISDICTION = 'EMPLOY_LIST_JURISDICTION';
export const ADD_EMPLOY = 'ADD_EMPLOY';
export const DELETE_EMPLOY = 'DELETE_EMPLOY';

export const RELATED_PROJECT = 'RELATED_PROJECT';
export const RELATED_REMOVE = 'RELATED_REMOVE';
export const EMPLOY_JUR_LIST = 'EMPLOY_JUR_LIST';
export const EMPLOY_JUR_LIST_ITEM_CHECKED_STATUS = 'EMPLOY_JUR_LIST_ITEM_CHECKED_STATUS';
export const EMPLOY_JUR_SAVE = 'EMPLOY_JUR_SAVE';
export const EMPLOY_RELATE_PROJECT_LIST = 'EMPLOY_RELATE_PROJECT_LIST';
export const RELATED_PROJECT_LIST = 'RELATED_PROJECT_LIST';
export const PROJECT_ROLE = 'PROJECT_ROLE';
export const RELATED_ADD = 'RELATED_ADD';
