export const ROLE_LIST_SCCUESS = 'ROLE_LIST_SCCUESS';
export const ROLE_UPDATE_SCCUESS = 'ROLE_UPDATE_SCCUESS';
export const ROLE_DETAIL_LIST  = 'ROLE_DETAIL_LIST';
export const IS_ADD_BISS_USER_ROLE  = 'IS_ADD_BISS_USER_ROLE';
export const UPDATE_BISS_USER_ROLE  = 'UPDATE_BISS_USER_ROLE';
export const ROLE_LIST_JURISDICTION  = 'ROLE_LIST_JURISDICTION';