export const SETTING_PLATFORM_ACTION = 'SETTING_PLATFORM_ACTION';
export const SETTING_ACTION_SUCCESS = 'SETTING_ACTION';
export const SETTING_CLAUSE_ACTION = 'SETTING_CLAUSE_ACTION';
export const SETTING_CLAUSE_SUCCESS = 'SETTING_CLAUSE_SUCCESS';
export const CLAUSE_EDIT_ACTION = 'CLAUSE_EDIT_ACTION';
export const CLAUSE_EDIT_SUCCESS = 'CLAUSE_EDIT_SUCCESS';

export const PLATFORM_ADD_OR_UPDATE_ACTION = 'PLATFORM_ADD_OR_UPDATE_ACTION';
export const PLATFORM_ADD_OR_UPDATE_STATE = 'PLATFORM_ADD_OR_UPDATE_STATE';

export const SETTING_AD_POS_LIST_ACTION = 'SETTING_AD_POS_LIST_ACTION';
export const SETTING_AD_POS_LIST_SUCCESS = 'SETTING_AD_POS_LIST_SUCCESS';

export const SETTING_AD_POS_UPDATE_ACTION = 'SETTING_AD_POS_UPDATE_ACTION';

export const SETTING_AD_CONTNET_LIST_ACTION = 'SETTING_AD_CONTNET_LIST_ACTION';
export const SETTING_AD_CONTNET_LIST_SUCCESS = 'SETTING_AD_CONTNET_LIST_SUCCESS';
export const SETTING_AD_CONTNET_STATE_ACTION = 'SETTING_AD_CONTNET_STATE_ACTION';
export const SETTING_AD_CONTNET_STATE_SUCCESS = 'SETTING_AD_CONTNET_STATE_SUCCESS';
export const SETTING_AD_CONTNET_ADD_ACTION = 'SETTING_AD_CONTNET_ADD_ACTION';
export const SETTING_AD_CONTNET_ADD_SUCCESS = 'SETTING_AD_CONTNET_ADD_SUCCESS';


export const SETTING_AD_CLEAR = 'SETTING_AD_CLEAR';

export const SETTING_POS_AND_PLATFORM_CLEAR = 'SETTING_POS_AND_PLATFORM_CLEAR';

export const SETTING_JURISDICTION = 'SETTING_JURISDICTION';


