export const PROJECT_ACTION = 'PROJECT_ACTION';
export const PROJECT_LIST = 'PROJECT_LIST';
export const PROJECT_DETAIL_ACTION = 'PROJECT_DETAIL_ACTION';
export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';
export const PROJECT_LIST_JURISDICTION = 'PROJECT_LIST_JURISDICTION';

export const COMPANY_UNIT_ACTION = 'COMPANY_UNIT_ACTION';
export const COMPANY_UNIT_LIST = 'COMPANY_UNIT_LIST';
export const UNIT_EMPLOYEE_ACTION = 'UNIT_EMPLOYEE_ACTION';
export const UNIT_EMPLOYEE_LIST = 'UNIT_EMPLOYEE_LIST';
export const UNIT_TEAM_ACTION = 'UNIT_TEAM_ACTION';
export const UNIT_TEAM_LIST = 'UNIT_TEAM_LIST';
export const UNIT_WORKER_ACTION = 'UNIT_WORKER_ACTION';
export const UNIT_WORKER_LIST = 'UNIT_WORKER_LIST';