export const SAAS_MANAGEMENT_ACTION = 'SAAS_MANAGEMENT_ACTION';
export const SAAS_MANAGEMENT_LIST = 'SAAS_MANAGEMENT_LIST';
export const HARDWARE_CODE_ACTION = 'HARDWARE_CODE_ACTION';
export const HARDWARE_CODE_LIST = 'HARDWARE_CODE_LIST';
export const HARDWARE_REGISTER_ACTION = 'HARDWARE_REGISTER_ACTION';
export const ADD_HARDWARE_REGISTER = 'ADD_HARDWARE_REGISTER';
export const SAAS_OPERATION_ACTION = 'SAAS_OPERATION_ACTION';
export const SAAS_OPERATION_SUCCESS = 'SAAS_OPERATION_SUCCESS';
export const HARDWARE_MONITORING_ACTION = 'HARDWARE_MONITORING_ACTION';
export const HARDWARE_MONITORING_LIST = 'HARDWARE_MONITORING_LIST';
export const SAAS_JURISDICTION = 'SAAS_JURISDICTION';

export const JOB_CARD_ACTION = 'JOB_CARD_ACTION';
export const JOB_CARD_LIST = 'JOB_CARD_LIST';
export const SEARCH_PRO_ACTION = 'SEARCH_PRO_ACTION';
export const SEARCH_PRO_LIST = 'SEARCH_PRO_LIST';
export const RELATED_PRO_ACTION = 'RELATED_PRO_ACTION';
export const RELATED_PRO_SUCCESS = 'RELATED_PRO_SUCCESS';