export const GET_CITY_LIST_ACTION = 'GET_CITY_LIST_ACTION';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_JUR = 'GET_CITY_LIST_JUR';

export const GET_CITY_UPDATE_ACTION = 'GET_CITY_UPDATE_ACTION';
export const GET_CITY_UPDATE_SUCCESS = 'GET_CITY_UPDATE_SUCCESS';

export const GET_CITY_ADD_ACTION = 'GET_CITY_ADD_ACTION';