export const REGION_SUCCESS = 'REGION_SUCCESS';
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const COUNTY_SUCCESS = 'COUNTY_SUCCESS';

export const REGION_OLD_SUCCESS = 'REGION_OLD_SUCCESS';
export const CITY_OLD_SUCCESS = 'CITY_OLD_SUCCESS';
export const COUNTY_OLD_SUCCESS = 'COUNTY_OLD_SUCCESS';


export const REGION_ERROR = 'REGION_ERROR';