export const INFO_ASSIS_MANAGE_LIST_ACTION = 'INFO_ASSIS_MANAGE_LIST_ACTION';
export const INFO_ASSIS_MANAGE_LIST_SUCCESS = 'INFO_ASSIS_MANAGE_LIST_SUCCESS';

export const INFO_ASSIS_MANAGE_EDIT_ACTION = 'INFO_ASSIS_MANAGE_EDIT_ACTION';
export const INFO_ASSIS_MANAGE_UPDATE = 'INFO_ASSIS_MANAGE_UPDATE';

export const INFO_ASSIS_MANAGE_TARTGET_LIST_ACTION = 'INFO_ASSIS_MANAGE_TARTGET_LIST_ACTION';
export const INFO_ASSIS_MANAGE_TARTGET_LIST_SUCCESS = 'INFO_ASSIS_MANAGE_TARTGET_LIST_SUCCESS';

export const INFO_ASSIS_MANAGE_FETCH_USER_ACTION = 'INFO_ASSIS_MANAGE_FETCH_USER_ACTION';
export const INFO_ASSIS_MANAGE_FETCH_USER_SUCCESS = 'INFO_ASSIS_MANAGE_FETCH_USER_SUCCESS';

export const INFO_ASSIS_MANAGE_CLEAR = 'INFO_ASSIS_MANAGE_CLEAR';


