export const PROJECT_TYPE_ACTION = 'PROJECT_TYPE_ACTION';
export const PROJECT_TYPE_LIST = 'PROJECT_TYPE_LIST';

export const PROVINCE_ACTION='PROVINCE_ACTION';
export const PROVINCE_SUCCESS='REGION_SUCCESS'; // 省
export const REGION_ACTION='CITY_ACTION';
export const REGION_SUCCESS='CITY_SUCCESS'; // 市
export const COUNTRY_ACTION='COUNTRY_ACTION';
export const COUNTRY_SUCCESS='COUNTY_SUCCESS'; // 区

export const GET_VALID_CODE_ACTION='GET_VALID_CODE_ACTION';
export const GET_VALID_CODE_SUCCESS='GET_VALID_CODE_SUCCESS'; // 验证码