export const APP_ACTION = 'APP_ACTION';
export const APP_ACTION_SUCCESS = 'APP_ACTION_SUCCESS';
export const APP_DELETE_ACTION = 'APP_DELETE_ACTION';
export const APP_DELETE_SUCCESS = 'APP_DELETE_SUCCESS';
export const DELETE_LABEL_ACTION = 'DELETE_LABEL_ACTION';
export const DELETE_LABEL_SUCCESS = 'DELETE_LABEL_SUCCESS';
export const ADD_LABEL_ACTION = 'ADD_LABEL_ACTION';
export const ADD_LABEL_SUCCESS = 'ADD_LABEL_SUCCESS';
export const UPDATE_CHECKBOX_ACTION = 'UPDATE_CHECKBOX_ACTION';
export const UPDATE_CHECKBOX_SUCCESS = 'UPDATE_CHECKBOX_SUCCESS';
export const AUDIT_ACTION = 'AUDIT_ACTION';
export const AUDIT_SUCCESS = 'AUDIT_SUCCESS';



export const APP_MANAGE_ACTION = 'APP_MANAGE_ACTION';
export const APP_MANAGE_SUCCESS = 'APP_MANAGE_SUCCESS';
export const APP_MANAGE_UPDATE_ACTION = 'APP_MANAGE_UPDATE_ACTION';
export const APP_MANAGE_UPDATE_SUCCESS = 'APP_MANAGE_UPDATE_SUCCESS';

export const APP_JURISDICTION = 'APP_JURISDICTION';
