export const INFO_ASSISTANT_LIST_ACTION = 'INFO_ASSISTANT_LIST_ACTION';
export const INFO_ASSISTANT_LIST_SUCCESS = 'INFO_ASSISTANT_LIST_SUCCESS';

export const INFO_ASSISTANT_EDIT_ACTION = 'INFO_ASSISTANT_EDIT_ACTION';

export const INFO_ASSISTANT_UPDATE = 'INFO_ASSISTANT_UPDATE';
export const INFO_ASSISTANT_JUR = 'INFO_ASSISTANT_JUR';