export const TEAM_MANAGEMENT_LIST = 'TEAM_MANAGEMENT_LIST';
export const TEAM_MANAGEMENT_SEARCH_LIST = 'TEAM_MANAGEMENT_SEARCH_LIST';
export const TEAM_MANAGEMENT_SEARCH_FAIL = 'TEAM_MANAGEMENT_SEARCH_FAIL';
export const TEAM_MANAGEMENT_SEARCH_ADD = 'TEAM_MANAGEMENT_SEARCH_ADD';
export const MEMBER_MANAGEMENT_LIST = 'MEMBER_MANAGEMENT_LIST';
export const TEAM_MANAGEMENT_LIST_JURISDICTION = 'TEAM_MANAGEMENT_LIST_JURISDICTION';
export const GROUP_DELETE = 'GROUP_DELETE';
