export const PERSONINFO = 'PERSONINFO';
export const PERSONINFO_ERROR = 'PERSONINFO_ERROR';
export const PERSONINFO_JURISDICTION = 'PERSONINFO_JURISDICTION';

// export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';