export const PLATFROM_MANAGE_JUR_LIST = 'PLATFROM_MANAGE_JUR_LIST';
export const PLATFROM_MANAGE_JURISDICTION = 'PLATFROM_MANAGE_JURISDICTION';
export const PLATFROM_MANAGE_JUR_DEPT = 'PLATFROM_MANAGE_JUR_DEPT';
export const PLATFROM_MANAGE_JUR_SEARCH = 'PLATFROM_MANAGE_JUR_SEARCH';
export const PLATFROM_MANAGE_JUR_SEARCH_CLEAR = 'PLATFROM_MANAGE_JUR_SEARCH_CLEAR';
export const PLATFROM_MANAGE_JUR_STATUS = 'PLATFROM_MANAGE_JUR_STATUS';
export const PLATFROM_MANAGE_JUR_INIT_LIST = 'PLATFROM_MANAGE_JUR_INIT_LIST';
export const PLATFROM_MANAGE_DELLIST_INIT = 'PLATFROM_MANAGE_DELLIST_INIT';
