export const EDUCATION_INFO_DETAIL_RES = 'EDUCATION_INFO_DETAIL_RES';
export const EDUCATION_INFO_SUCCESS = 'EDUCATION_INFO_SUCCESS';
export const EDUCATION_ECHART_JURISDICTION = 'EDUCATION_ECHART_JURISDICTION';