
const LOGINRECORD_SUCCESS='LOGINRECORD_SUCCESS';
const  LOGINRECORD_JUR='LOGINRECORD_JUR';
const LOGINRECORD_ACTION='LOGINRECORD_ACTION';
const LOGINRECORD_LIST='LOGINRECORD_LIST';

export {
    LOGINRECORD_SUCCESS,
    LOGINRECORD_JUR,
    LOGINRECORD_ACTION, 
    LOGINRECORD_LIST, // 用户列表
};