const PERMISSLIST = 'PERMISSLIST';
const PERMISSLIST_ERROR = 'PERMISSLIST_ERROR';
const USERLIST = 'USERLIST';
const USERLIST_ERROR = 'USERLIST_ERROR';
const ROLELIST = 'ROLELIST';
const ROLELIST_ERROR = 'ROLELIST_ERROR';
const PERMISSLIST_JURISDICTION = 'PERMISSLIST_JURISDICTION';

export {
    PERMISSLIST,
    PERMISSLIST_ERROR,
    USERLIST,
    USERLIST_ERROR,
    ROLELIST,
    ROLELIST_ERROR,
    PERMISSLIST_JURISDICTION
}