const ASSISTANT_INFORM_LIST = 'ASSISTANT_INFORM_LIST';
const ASSISTANT_INFORM_ERROR = 'ASSISTANT_INFORM_ERROR';
const INFORM_DETAIL_TITLE = 'INFORM_DETAIL_TITLE';
const INFORM_DETAIL_LIST = 'INFORM_DETAIL_LIST';
const INFORM_DETAIL_SELROLE = 'INFORM_DETAIL_SELROLE';
const INFORM_DETAIL_SELUSER = 'INFORM_DETAIL_SELUSER';
const INFORM_DETAIL_INFORMOBJ_LIST = 'INFORM_DETAIL_INFORMOBJ_LIST';
const ASSISTANT_INFORM_JURISDICTION = 'ASSISTANT_INFORM_JURISDICTION';

export{
    ASSISTANT_INFORM_LIST,
    ASSISTANT_INFORM_ERROR,
    INFORM_DETAIL_TITLE,
    INFORM_DETAIL_LIST,
    INFORM_DETAIL_SELROLE,
    INFORM_DETAIL_SELUSER,
    INFORM_DETAIL_INFORMOBJ_LIST,
    ASSISTANT_INFORM_JURISDICTION,
}