export const FORGET_VALID_ACTION = 'FORGET_VALID_ACTION';
export const FORGET_NEXT_VALID_ACTION = 'FORGET_NEXT_VALID_ACTION';
export const FORGET_NEXT_VALID_SUCCESS = 'FORGET_NEXT_VALID_SUCCESS';
export const FORGET_NEXT_VALID_STATUS = 'FORGET_NEXT_VALID_STATUS';

export const RESET_ACTION = 'RESET_ACTION';
export const RESET_SUCCESS = 'RESET_SUCCESS';