export const DASHBOARD_USER_INFO_ACTION = 'DASHBOARD_USER_INFO_ACTION';
export const DASHBOARD_USER_INFO_SUC = 'DASHBOARD_USER_INFO_SUC';

export const DASHBOARD_LIST_ACTION = 'DASHBOARD_LIST_ACTION';
export const DASHBOARD_LIST_SUC = 'DASHBOARD_LIST_SUC';

export const DASHBOARD_BULLETEDLIST_ACTION = 'DASHBOARD_BULLETEDLIST_ACTION';
export const DASHBOARD_BULLETEDLIST_SUC = 'DASHBOARD_BULLETEDLIST_SUC';

export const DASHBOARD_JUR = 'DASHBOARD_JUR';