export const CAMERA_LIST_SUCCESS = 'CAMERA_LIST_SUCCESS';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const CAMERA_DELETE_SUCCESS = 'CAMERA_DELETE_SUCCESS';
export const CAMERA_LIST_JURISDICTION = 'CAMERA_LIST_JURISDICTION';