export const PROJECT_DATA_TYPE_ACTION = 'PROJECT_DATA_TYPE_ACTION';
export const PROJECT_DATA_TYPE_SUCCESS = 'PROJECT_DATA_TYPE_SUCCESS';
export const PROJECT_DATA_TYPE_JUR = 'PROJECT_DATA_TYPE_JUR';

export const PROJECT_DATA_DICTION_ACTION = 'PROJECT_DATA_DICTION_ACTION';
export const PROJECT_DATA_DICTION_SUCCESS = 'PROJECT_DATA_DICTION_SUCCESS';

export const PROJECT_DATA_DELETE_ACTION = 'PROJECT_DATA_DELETE_ACTION';
export const PROJECT_DATA_UPDATE = 'PROJECT_DATA_UPDATE';

export const PROJECT_DATA_EDIT_ACTION = 'PROJECT_DATA_EDIT_ACTION';

export const PROJECT_DATA_CLEAR_STORE = 'PROJECT_DATA_CLEAR_STORE';