export const PROJECT_ROLE_LIST_ACTION = 'PROJECT_ROLE_LIST_ACTION';
export const PROJECT_ROLE_LIST_SUCCESS = 'PROJECT_ROLE_LIST_SUCCESS';
export const PROJECT_ROLE_LIST_JUR = 'PROJECT_ROLE_LIST_JUR';

export const PROJECT_ROLE_SAVE_ACTION = 'PROJECT_ROLE_SAVE_ACTION';
export const PROJECT_ROLE_SAVE_SUCCESS = 'PROJECT_ROLE_SAVE_SUCCESS';

export const PROJECT_ROLE_EDIT_ACTION = 'PROJECT_ROLE_EDIT_ACTION';
export const PROJECT_ROLE_DEL_ACTION = 'PROJECT_ROLE_DEL_ACTION';
