export const QUALITY_LIST = 'QUALITY_LIST';
export const QUALITY_PROJECT_ERROR = 'QUALITY_PROJECT_ERROR';
export const QUALITY_ADD = 'QUALITY_ADD';
export const QUALITY_MARK = 'QUALITY_MARK';
export const PRO_QUALITY_JURISDICTION = 'PRO_QUALITY_JURISDICTION';
