export const VALID_CODE_SUCCESS = 'VALID_CODE_SUCCESS';
export const VALID_ERROR_MSG = 'VALID_ERROR_MSG';
export const CLEAR_MSG = 'CLEAR_MSG';
export const FORGET_RESET_SUCCESS = 'FORGET_RESET_SUCCESS';