const EDU_ASSIS_DETAIL_SUCCESS = 'EDU_ASSIS_DETAIL_SUCCESS';
// 教育助手详情
const EDU_ASSIS_DETAIL_LIST_ACTION='EDU_ASSIS_DETAIL_LIST_ACTION';
const EDU_ASSIS_DETAIL_LIST='EDU_ASSIS_DETAIL_LIST';
const EDU_ASSIS_DETAIL_DEL_ACTION='EDU_ASSIS_DETAIL_DEL_ACTION';
const EDU_ASSIS_DETAIL_SAVE_ACTION='EDU_ASSIS_DETAIL_SAVE_ACTION';

const EDU_ASSIS_MODAL_TOPICS_ACTION='EDU_ASSIS_MODAL_TOPICS_ACTION';
const EDU_ASSIS_MODAL_TOPICS='EDU_ASSIS_MODAL_TOPICS';

export{
    EDU_ASSIS_DETAIL_SUCCESS,
    EDU_ASSIS_DETAIL_LIST_ACTION,EDU_ASSIS_DETAIL_LIST,
    EDU_ASSIS_DETAIL_DEL_ACTION,EDU_ASSIS_DETAIL_SAVE_ACTION,

    EDU_ASSIS_MODAL_TOPICS_ACTION,EDU_ASSIS_MODAL_TOPICS,
}