export const EDUCATION_LIST = 'EDUCATION_LIST';
export const EDUCATION_LIST_ERROR = 'EDUCATION_LIST_ERROR';
export const EDIT_EDU_LIST = 'EDIT_EDU_LIST';
export const COPY_LIST = 'COPY_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const EDUCATION_LIST_JURISDICTION = 'EDUCATION_LIST_JURISDICTION';