export const SYSTEM_POWER_SEARCH_USER_ACTION = 'SYSTEM_POWER_SEARCH_USER_ACTION';
export const SYSTEM_POWER_SEARCH_USER_SUCCESS = 'SYSTEM_POWER_SEARCH_USER_SUCCESS';

export const SYSTEM_POWER_CLEAR_USER = 'SYSTEM_POWER_CLEAR_USER';

export const SYSTEM_POWER_ADD_AUTH_ACTION = 'SYSTEM_POWER_ADD_AUTH_ACTION';
export const SYSTEM_POWER_UPDATE_STATE = 'SYSTEM_POWER_UPDATE_STATE';

export const SYSTEM_POWER_AUTH_LIST_ACTION = 'SYSTEM_POWER_AUTH_LIST_ACTION';
export const SYSTEM_POWER_AUTH_LIST_SUCCESS = 'SYSTEM_POWER_AUTH_LIST_SUCCESS';

export const SYSTEM_POWER_UPDATE_STATE_ACTION = 'SYSTEM_POWER_UPDATE_STATE_ACTION';

export const SYSTEM_POWER_JUR = 'SYSTEM_POWER_JUR';

