const AUTHORITYLIST = 'AUTHORITYLIST';
const AUTHORITYLIST_ERROR = 'AUTHORITYLIST_ERROR';
const USERLIST = 'USERLIST';
const USERLIST_ERROR = 'USERLIST_ERROR';
const ROLELIST = 'ROLELIST';
const ROLELIST_ERROR = 'ROLELIST_ERROR';
const AUTHORITYLIST_JURISDICTION = 'AUTHORITYLIST_JURISDICTION';
const ACCESS_PLAN_UPDATE = 'ACCESS_PLAN_UPDATE';

export{
    AUTHORITYLIST,
    AUTHORITYLIST_ERROR,
    USERLIST,
    USERLIST_ERROR,
    ROLELIST,
    ROLELIST_ERROR,
    AUTHORITYLIST_JURISDICTION,
    ACCESS_PLAN_UPDATE
}