export const EMPLOY_GROUP_LIST = 'EMPLOY_GROUP_LIST';
export const GROUP_SEARCH_LIST = 'GROUP_SEARCH_LIST';
export const GROUP_SEARCH_FAIL = 'GROUP_SEARCH_FAIL';
export const GROUP_SEARCH_ADD = 'GROUP_SEARCH_ADD';
export const EMPOLY_MEMBER_LIST = 'EMPOLY_MEMBER_LIST';
export const EMPLOY_GROUP_JURISDICTION = 'EMPLOY_GROUP_JURISDICTION';
export const EMPOLY_GROUP_DELETE = 'EMPOLY_GROUP_DELETE';
