export const IS_PHONE_REGISTER = 'IS_PHONE_REGISTER';

export const GET_VALID_CODE_SUCCESS = 'GET_VALID_CODE_SUCCESS';
export const GET_VALID_CODE_REGISTER_SUCCESS = 'GET_VALID_CODE_REGISTER_SUCCESS';
export const VALID_ERROR_MSG = 'VALID_ERROR_MSG';
export const VALID_REGISTER_ERROR_MSG = 'VALID_REGISTER_ERROR_MSG';
export const USER_COMMON_CLEAR = 'USER_COMMON_CLEAR';
export const GET_VALID_CODE_INFO_SUCCESS = 'GET_VALID_CODE_INFO_SUCCESS';
export const VALID_CODE_INFO_ERROR = 'VALID_CODE_INFO_ERROR';
